Adding license file and copyright headers
qiime2/busywork pull request #125
Opened 2021-04-29 23:27 UTC by lizgehret

Added missing license file and copyright headers

2021-04-30 00:15 UTC, lizgehret commented
Ran flake8 and made necessary updates.

2021-05-05 23:25 UTC, thermokarst requested changes
This is great! I have marked two instances of a _very minor_ issue that should be resolved here prior to merging, but overall this looks great - good work!

2021-05-05 23:25 UTC, thermokarst commented on ci/master/template.py
> +# !/usr/bin/env python
The [hashpling](https://en.wikipedia.org/wiki/Shebang_(Unix)) needs to be at the top of the file (this tells your shell what executable to use when running the script). `q2lint` knows how to read/lint this, so you should be able to just move this up to the first line. Also, please note that it is `#!/usr/bin/env python`, not `# !/usr/bin/env python` - that little space can make a world of a difference when running the script!

```suggestion
#!/usr/bin/env python

# ----------------------------------------------------------------------------
# Copyright (c) 2017-2021, QIIME 2 development team.
#
# Distributed under the terms of the Modified BSD License.
#
# The full license is in the file LICENSE, distributed with this software.
# ----------------------------------------------------------------------------
```

2021-05-05 23:25 UTC, thermokarst commented on extra/github/template.py
> +# !/usr/bin/env python
Same comment as above, I'm marking here so that it makes it onto your TODO list!

2021-05-06 15:24 UTC, thermokarst commented on ci/master/template.py
> +# !/usr/bin/env python
Hey @lizgehret, I just edited my suggestion above, there was an extra linebreak between the hashpling and the header line, which is not valid q2lint material.

2021-05-06 15:24 UTC, lizgehret commented on extra/github/template.py
> +# !/usr/bin/env python
Thanks @thermokarst! Accepted and submitted your changes.

2021-05-06 15:32 UTC, thermokarst commented on extra/github/template.py
> +# !/usr/bin/env python
Thanks @lizgehret - please see my note above - there was a typo in my code suggestion.

2021-05-06 15:43 UTC, lizgehret reviewed
Removing line breaks after hashplings

2021-05-06 15:53 UTC, thermokarst approved these changes
Great, thanks so much!

2021-05-06 15:53 UTC, merged